-- Table: public.contracts

DROP TABLE IF EXISTS public.contracts;
CREATE TABLE public.contracts
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(255) COLLATE pg_catalog."default",
    address character varying(255) COLLATE pg_catalog."default",
    collateral_token_name character varying(255) COLLATE pg_catalog."default",
    collateral_token_symbol character varying(255) COLLATE pg_catalog."default",
    collateral_token_address character varying(255) COLLATE pg_catalog."default",
    oracle_query text COLLATE pg_catalog."default",
    is_settled boolean,
    collateral_pool_balance bigint,
    expiration_timestamp bigint,
    price_cap bigint,
    price_floor bigint,
    price_decimal_places integer,
    last_trade_price bigint,
    last_queried_price bigint,
    qty_multiplier bigint,
    reference_asset character varying(255) COLLATE pg_catalog."default",
    is_whitelisted boolean
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.contracts
    OWNER to market_admin;

-- Index: address
-- DROP INDEX IF EXISTS public.address;
CREATE INDEX address
    ON public.contracts USING btree
    (address COLLATE pg_catalog."default")
    TABLESPACE pg_default;

-- Index: name
-- DROP INDEX IF EXISTS public.name;
CREATE INDEX name
    ON public.contracts USING btree
    (name COLLATE pg_catalog."default")
    TABLESPACE pg_default;

GRANT ALL ON SEQUENCE public.contracts_id_seq TO lambda_user_test;
GRANT ALL ON TABLE public.contracts TO lambda_user_test;